map: "warehouse"
world: "warehouse"
rviz_file: "sim_env.rviz"

robots_config:
  - robot1_type: "turtlebot3_waffle"
    robot1_global_planner: "theta_star"
    # a_star(containing Dijkstra and GBFS) d_star_lite d_star graph_planner jump_point_search lazy_theta_star lpa_star theta_star voronoi informed_rrt rrt_connect rrt_star rrt sample_planner
    robot1_local_planner: "dwa"
    # pid dwa
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "0.0"

# plugins:
  # pedestrians: "pedestrian_config.yaml"
  # obstacles: "obstacles_config.yaml"
  # map_layers: "maps_config.yaml"
